# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
  - requirements: requirements.txt
  - path: .  # install spinegeneric itself so it can be imported

# The build happens in the docs/ directory
sphinx:
  configuration: docs/conf.py

# Other formats to produce, in addition to html
formats:
  - pdf
  - epub
